# Generated by Django 5.2 on 2025-04-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('technology', 'Technology'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
